server {
    listen 80;
    server_name localhost;

    root /config/www/;
    index index.html;

    location /static/ {
        alias /config/www/static/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

